### ISSUE TITLE
Class 'DualAnimationLoopController' has no instance getter 'isActive'

### ISSUE THREAD

**Issue by ghost** [flutter-institute/looping-flare-animations#1]
Hi! I am getting this error:

`Class 'DualAnimationLoopController' has no instance getter 'isActive'.
Receiver: Instance of 'DualAnimationLoopController'
Tried calling: isActive`

Can you help me solve this? Thank you!

**Comment by ghost** [comment]
Hi! I solved it using the FlareController as a mixin. Here is my code for anyone having the same problem:

`import 'package:flare_dart/math/mat2d.dart';
import 'package:flare_flutter/flare.dart';
import 'package:flare_flutter/flare_actor.dart';
import 'package:flare_flutter/flare_controller.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import '../styles.dart';

class AnimationScreen extends StatefulWidget {
  @override
  _AnimationScreenState createState() => _AnimationScreenState();
}

class _AnimationScreenState extends State<AnimationScreen> with FlareController {
  bool _looping = false;
  double _duration = 0.0;
  ActorAnimation _startAnimation;
  ActorAnimation _loopAnimation;
  double _mix = 1.0;

  @override
  void initialize(FlutterActorArtboard artboard) {
    _startAnimation = artboard.getAnimation('StartAnimation');
    _loopAnimation = artboard.getAnimation('LoopAnimation');
  }

  @override
  bool advance(FlutterActorArtboard artboard, double elapsed) {
    _duration += elapsed;

    if (!_looping) {
      if (_duration < _startAnimation.duration) {
        _startAnimation.apply(_duration, artboard, _mix);
      } else {
        _looping = true;
        _duration -= _startAnimation.duration;
      }
    }

    if (_looping) {
      _duration %= _loopAnimation.duration;
      _loopAnimation.apply(_duration, artboard, _mix);
    }

    return true;
  }

  @override
  void setViewTransform(Mat2D viewTransform) {}

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Styles.primaryColorDark,
      padding: EdgeInsets.all(25.0),
      child: FlareActor(
        'assets/animations/splash.flr',
        alignment: Alignment.center,
        fit: BoxFit.contain,
        animation: 'StartAnimation',
        controller: this,
        isPaused: !mounted,
      ),
    );
  }
}
`
Regards!

**Comment by killermonk** [comment]
Feel free to create a branch and submit a PR :)
